title: "NHC #3"
description: "Règlement officiel de la Nuclear Haunted Cup #3 : Apocalypse"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://nuclear-live.github.io"
baseurl: "/nhc3-reglement"

search_enabled: true
heading_anchors: true

color_scheme: apocalypse

nav_external_links:
  - title: Nuclear_Live sur Twitch
    url: https://www.twitch.tv/nuclear_live
    hide_icon: false
    opens_in_new_tab: true

favicon_ico: "/nhc3-reglement/logo-nuclear-live.png"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      has_toc: false
